# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-06-09 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_userinfo_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
